/**
 * How to read this config file.
 *
 */
module.exports.hSettings = {
    global: {
        nSeedID:1000000
        ,sLanguage:'en'
        ,aEmergencyEmails:['s2.d.young@gmail.com']
        ,sLogLevel:'debug'
        ,hOptions:{
            MySql:{
                sSchema:'nordis',
                sHost:'localhost',
                sUser:'root',
                nMaxConnections:10,
                nTimeoutMilliseconds:10000,
                bDebugMode:false,
                bSkip:false
            },
            Redis:{
                sWriteServer:'127.0.0.1',
                nWritePort:6379,
                nMaxConnections:200,
                nTimeoutMilliseconds:30000,
                nReapIntervalMilliseconds:5000,
                bDebugMode:false,
                bSkip:false
            }
        }
        ,hClasses:{
            User:{
                hProperties:{
                    id:{
                        sType:'Number',
                        bUnique:true
                    }
                    ,sid:{
                        sType:'String'
                        ,bUnique:true
                        ,nLength:36
                    }
                    ,created:{
                        sType:'Timestamp'
                        ,bOnCreate:true
                    }
                    ,updated:{
                        sType:'Timestamp'
                        ,bOnUpdate:true
                    }
                    ,name:{
                        sType:'String'
                    }
                    ,password:{
                        sType:'String'
                        ,bPrivate:true
                    }
                    ,email:{
                        sType:'String'
                        ,bUnique:true
                    }
                    ,referrer_id:{
                        sType:'Number'
                    }
                }
                ,nClass:1
                ,hExtras:{
                    nPoints:{sType:'Increment'}
                    ,friends:{
                        sType:'Collection'
                        ,sClass:'Friend'
                        ,sOrderBy:'rank'
                        ,bReverse:true
                        ,fnQuery:function(oSelf){
                            return {user_id:oSelf.getNumKey()}
                        }
                    }
                    ,referring_user:{
                        sType:'Object'
                        ,sClass:'User'
                        ,aKey:['referrer_id','id']
                        ,fnQuery:function(oObj){
                            return {id:oObj.get('referrer_id')}
                        }
                    }
                }
            }
            ,Friend:{
                hProperties:{
                    id:{
                        sType:'Number',
                        bUnique:true
                    }
                    ,user_id:{
                        sType:'Number'
                    }
                    ,friend_id:{
                        sType:'Number'
                    }
                    ,rank:{
                        sType:'Number'
                    }
                }
                ,nClass:2
                ,hExtras:{
                    user:{
                        sType:'Object'
                        ,sClass:'User'
                        ,aKey:['user_id','id']
                        ,fnQuery:function(oSelf){
                            return {id:oSelf.get('user_id')}
                        }
                    }
                    ,friend_user:{
                        sType:'Object'
                        ,sClass:'User'
                        ,aKey:['friend_id','id']
                        ,fnQuery:function(oSelf){
                            return {nID:oSelf.get('friend_id')}
                        }
                    }
                }
            }
            ,Sale:{
                nClass:3
                ,hProperties:{
                    id:{bUnique:true,sType:'Number'}
                    ,user_id:{sType:'Number'}
                    ,amount:{sType:'Float',nMax:20,nScale:2}
                }
                ,sAdapterPath:'example/overrides/adapter/Sale.js'
                ,sClassPath:'example/overrides/class/Sale.js'
            }
        }
        ,hErrorStrings:{
            500:{
                en:'Malformed request.'
            }
        }
    }
};
