FORMAT: 1A
HOST: http://api.example.com

# Nordis Sample API
This API is a simple output of the classes provided in this simple configuration example. No authentication is required for any endpoint, but real-world examples should include it.

# Group User
Users are usually people, but can sometimes be bots. Users can be created, saved and deleted. These methods are marked unprotected, but a security layer can be applied via custom handler or here in configuration using the fnValidate function.

## User [/user/{id}]
Retrieve, update and delete user.

+ Parameters
    + id (required,Number,`1`) ... 

### Update, or Create, User [POST]
You can also create a NEW user by leaving the sid out.
+ Response 200 (application/json)
    + Body

            {"sClass":"User","nClass":1,"id":1,"sid":"Yf8uIoP","created":1389625960,"updated":1389625960,"name":"Joe User","email":"joe@gmail.com","referrer_id":null,"balance":"NaN"}


### Retrieve a User [GET]
You can retrieve any of the 'hExtras' configured for the class using the hExtras parameter in the GET call. In the following example, we want to retrieve the user's 'follows' collection up to a total of ONE record (nSize:1). On that follower, we want the related follower_user property (which is a User object).

            {"hExtras":{follows:{nSize:1,hExtras:{follower_user:true}}}}
+ Response 200 (application/json)
    + Body

            {"sClass":"User","nClass":1,"id":1,"sid":"Yf8uIoP","created":1389625960,"updated":1389625960,"name":"Joe User","email":"joe@gmail.com","referrer_id":null,"balance":"NaN"}


### Delete a User [DELETE]
+ Response 204

# Group Follow
Follow objects are pointers to Users. The initiator of the follow is found on the 'follower_user' extra, while the recipient is the 'followed_user.'

## Follow [/user/{id}/follows]
Retrieves collection of follows for the passed-in user.

+ Parameters
    + id (required,Number,`3`) ... 

### Retrieve Follow Collection [GET]
This api call is an example of how to define a custom function (fnApiCallProcessor) to track stats or check security credentials on an endpoint. Also, this example has a custom output function (fnApiCallOutput) which customizes what the returning document looks like. Both are defined in the config file.
+ Response 200 (application/json)
    + Body

            {"sClass":"Follow","aObjects":[{"id":3,"followed_id":1,"follower_id":2,"rank":1,"follower_user":{"id":2,"sid":"H0Jd56g6","created":1389625960,"updated":1389625960,"name":"Joe Follower","email":"follower@gmail.com","referrer_id":"1"}}],"nTotal":1}


# Group Stat
Analytics endpoints available for retrieval via api. (To disable, add bApi:false to stat config; to protect, add fnApiCallProcessor function to config to validate the request).

## Stat [/stat/users/{grain}]
Total number of new user accounts created during the period.

+ Parameters
    + grain (required,String,`hour`) ... String name of desired granularity. Acceptable values include hour, day, month, year or all.

### undefined [GET]
+ Response 200 (application/json)
    + Body

            {"sClass":"Stat"}


## Stat [/stat/uniques/{grain}]
Total number of unique users active during the period. Multiple hits by one user count as one unique.

+ Parameters
    + grain (required,String,`hour`) ... String name of desired granularity. Acceptable values include hour, day, month, year or all.

### undefined [GET]
+ Response 200 (application/json)
    + Body

            {"sClass":"Stat"}


## Stat [/stat/hits/{grain}]
Total number of hits to the web, including page-level filters.

+ Parameters
    + grain (required,String,`hour`) ... String name of desired granularity. Acceptable values include hour, day, month, year or all.

### undefined [GET]
+ Response 200 (application/json)
    + Body

            {"sClass":"Stat"}


## Stat [/stat/api_requests/{grain}]
Total number of hits to the api, regardless of user.

+ Parameters
    + grain (required,String,`hour`) ... String name of desired granularity. Acceptable values include hour, day, month, year or all.

### undefined [GET]
+ Response 200 (application/json)
    + Body

            {"sClass":"Stat"}


